project:
  type: website

website:
  navbar:
    title: false
    left:
      - href: trieu-le.qmd
        text: Trieu Le
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: publications.qmd
        text: Publications
      - href: bioinformatics/index.qmd
        text: Bioinformatics for "Dumb me"
      - href: thoughts/index.qmd
        text: Thoughts


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true