project:
  type: website

website:
  title: "Trieu Le"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About Me
      - href: publications.html
        text: Publications
      - href: bioinformatics/index.html
        text: Bioinformatics for Dummies
      - href: thoughts/index.html
        text: Thoughts
      - href: cv.html
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true